---
title: "Simple document"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
```


## Import some data

```{r}
litters_df = read_csv("data/FAS_litters.csv")
```

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df) # use this function in janitor package without loading everything
```

```{r}
litters_df

head(litters_df)
tail(litters_df) # make sure not to end up with empty rows
```

```{r, eval = FALSE}
view(litters_df) # eval = F not to print out
```

```{r}
skimr::skim(litters_df)
```

## Argumetns in 'read_csv'

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE,
    na = "Low8"
  )
```

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```

