---
title: "Tidy Data"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```


## Import some data

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
```

```{r}
pulse_tidy_data = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi",
    names_prefix = "bdi_score_") %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit))
```


## pivot_wider

```{r}
analysis_df =
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a", "b", "a", "b"),
    group_mean = c(4, 8, 3,6)
  )

analysis_df %>% 
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  ) %>%
  knitr::kable() # make a table
```


## bind_rows

```{r}
fellowship_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_rings")

two_towers_df = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_df = 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")

lotr_df = 
  bind_rows(fellowship_df, two_towers_df, return_df) %>% 
  janitor::clean_names() %>% # make the variable name to lowercase
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>% 
  relocate(movie) # Change column order
```




## joins

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  separate(group, into = c("dose", "day_of_tx"), 3) %>% # separate the first column into two columns
  relocate(litter_number) %>% 
  mutate(dose = str_to_lower(dose))


pups_df = 
  read_csv("data/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sex = recode(sex, '1' = "male", '2' = "female")) # recode exist value to new value
```

Let's join these up!

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  relocate(litter_number, dose, day_of_tx)
```

# always use bind_rows() instead rbind()
# always use read_csv() intead of read.csv()
# always use pivot_longer() instead of gather()
# always use pivot_wider() instead of spread()